# Generated by Django 2.2 on 2022-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Username'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
