# Generated by Django 2.2 on 2022-11-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20221113_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
