# Generated by Django 4.1.3 on 2022-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20221118_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Can publish'),), 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tag'),
        ),
    ]
