# Generated by Django 4.1.3 on 2022-11-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_profile_date_of_birth_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Can verify'),)},
        ),
    ]
