# Generated by Django 4.1.3 on 2022-11-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20221124_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('verify_profile', 'Can verify'),)},
        ),
    ]
